### ISSUE TITLE
Change skipTargetBlank to skipNoOpener

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/link-hijacker#2]
As @yoshuawuyts [pointed out](https://github.com/yoshuawuyts/nanohref/issues/3#issuecomment-311922994), `rel="noopener"` is preferred to `target="_blank"` for opening links in new tabs.

The option should apply to *both* patterns; but we should change the option name to favor the better pattern.

**Comment by davidtheclark** [comment]
I misunderstood the issue. `rel="noopener"` is supposed to be used *in combination with `target="_blank"`*. On its own, it will not tell the browser to open a new tab.

https://mathiasbynens.github.io/rel-noopener/
https://developers.google.com/web/tools/lighthouse/audits/noopener

**Comment by yoshuawuyts** [comment]
Oops, look like I misunderstood as well then haha
